### ISSUE TITLE
Incredible Job!

### ISSUE THREAD

**Issue by MadMax389** [gaugo87/PIXEstL#3]
Thank you for sharing this. I've been playing around with it the last two days. I do have a question about calibrating my own filaments. I printed the calibration swatches, but I'm having trouble with the light source and getting good HSL values. I'm getting very different hue numbers based in the thickness of the swatch. For IIIDMax Fuchsia I used this image in which white is not really white and the color fildelity is terrible
![image](https://github.com/gaugo87/PIXEstL/assets/96731892/4d29dc6d-93e4-4aaf-84fd-5babc5d8a52d)
I generated these values.
![image](https://github.com/gaugo87/PIXEstL/assets/96731892/db0ce3a3-6beb-4cb4-a927-857601752ad0)

I noticed in your .json file, your hue and saturation numbers are very close together with lightness decreasing evenly with thickness. Did you measure these values, or estimate them? I've tried different light sources and color balancing the image, but not having much luck. I thought about using the manufacturer's value and then eyeballing the saturation and lightness values. Thanks for your help.
![image](https://github.com/gaugo87/PIXEstL/assets/96731892/6735629c-470b-4319-8c2b-c7be9f87993f)

**Comment by MadMax389** [comment]
Thank you for the suggestions. I may need a better camera :)

**Comment by gaugo87** [comment]
Hi,

If you can't change the camera, another suggestion might be to make manual corrections. If you tell me that your light is white but appears yellow in photos, then you could perhaps manually remove the yellow.

For example, when I take the value of your white, I find a yellow value of 22.

So, you might consider subtracting 22 from yellow (via convertacolor.com) for all your values.

(I'm not a photographer or a lighting specialist, so I'm not sure how valid this advice is. 😜)

**Comment by MadMax389** [comment]
I think my main problem is that I didn't realize I was using a warm led source, hence the yellow. I replaced it for white and then did a white balance correction in post processing. I was then able to do an average color pick over a small area instead of just one pixel. The following image is a Bambu Magenta swatch that matches your h and s values very closely which gives me some confidence that I'm on the right track for my own filaments. Once I complete the filament .json, I'll do some test prints comparing BL filaments to my own CMYK filaments. Thanks so much for your help.
![image](https://github.com/gaugo87/PIXEstL/assets/96731892/50147dfc-c3f6-4c6a-ae22-fa6ae0fe9591)
![image](https://github.com/gaugo87/PIXEstL/assets/96731892/409d9766-edd3-420b-956d-fd67a4ce7324)

**Comment by gaugo87** [comment]
Great !
